#spring:
# application:
#  name: product-catalog
# data:
#  mongodb:
#    database: product-catalog
#    host: localhost
#    port: "27017"
#    uri: mongodb://localhost/product-catalog
#    username: ""
# eureka:
#  client:
#  register-with-eureka: "true"
#  fetch-registry: "true"
#  serviceUrl:
#    defaultZone: http://localhost:8761/eureka/
server:
 port: "9072"